version: "3.0"
services:
  angularjs:
    build: .
    image: angularjs:latest
    container_name: App
    ports:
      - 80:4200/tcp
    volumes:
      - ./youApp:/home/app
    working_dir: /home/app
    command: ng serve --host 0.0.0.0
