version: "3.0"
services:
  angularjs:
    build: .
    image: angularjs:latest
    container_name: admin
    ports:
      - 4200:80/tcp
    volumes:
      - ./yourApp:/home/app
    working_dir: /home/app
    command: ng serve --host 0.0.0.0
